version: '3.9'
services:
    go:
        container_name: go
        build: 
            context: .
            target: release
        volumes:
            - ./src:/opt/src/
        ports: 
            - 8080:8080
